apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/hello-docker
  newTag: 36462c5b5a26bfcf92be4345dc129311c0097889
resources:
- ../base
