apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/hello-docker
  newTag: 7ee2366bc4cb34f2a9b2ea8740dcda87db49504a
resources:
- ../base
