apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: invaleed/hello-docker
  newTag: a6202da546910d1bb27f32212362f27e2871766a
resources:
- ../base
